assign_service_routes/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from users.views import Login
from users.views import Logout


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),
    path('routes/', include('routes.urls', namespace="routes")),
    path('services/', include('services.urls', namespace="services")),
]

routes/urls.py
from django.urls import path
from routes.views import ListRoutes
from routes.views import AttendService

app_name = 'routes'

urlpatterns = [
    path('', ListRoutes.as_view(), name="list_routes"),
    path('attend-service/<int:code_route>/', AttendService.as_view(), name="attend_service"),
]

routes/models.py
from django.db import models
from technicians.models import Technician
from services.models import Service


class Route(models.Model):
    technician = models.ForeignKey(Technician, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    created = models.DateTimeField(
        'created at',
        auto_now_add=True,
        help_text='Date time on which the route was created.'
    )

    def __str__(self):
        """Return username."""
        return "%s-%s %s" % (self.service.type.name, self.technician.user.first_name, self.technician.user.last_name)

    class Meta:
        verbose_name_plural = "Routes"
        verbose_name = "Route"
        ordering = ['-created']

routes/admin.py
from django.contrib import admin
from routes.models import Route


@admin.register(Route)
class RouteAdmin(admin.ModelAdmin):
    list_display = ('technician', 'service', 'created')
    search_fields = ('service__type__name', 'technician__user__first_name',  'technician__user__last_name')
    list_filter = ('service__type__name', 'technician__user__first_name',  'technician__user__last_name')
    ordering = ('-created',)

routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    name = 'routes'

routes/create_routes.py
from technicians.models import Technician
from services.models import Service
from routes.models import Route
from multiprocessing import Process
from multiprocessing import Queue
from multiprocessing import cpu_count
from queue import Empty
from datetime import timedelta
from datetime import datetime
from django.utils.timezone import get_current_timezone
from haversine import haversine
from haversine import Unit


def search_last_rute(service, technician):
    date_now = datetime.now(tz=get_current_timezone())
    previous_services = Route.objects.filter(technician=technician.id,
                                             created__year=date_now.year,
                                             created__month=date_now.month,
                                             created__day=date_now.day,
                                             service__demand__lte=service.demand).order_by('-service__demand')
    if len(previous_services) > 0:
        return previous_services[0]
    return None


def search_current_technician_position(service, technician):
    last_route = search_last_rute(service, technician)

    if last_route is not None:
        latitude = last_route.service.client.latitude
        longitude = last_route.service.client.longitude
        return [latitude, longitude]
    return None


def evaluate_technician_availability(service, technician):
    last_route = search_last_rute(service, technician)

    if last_route is not None:
        time_delta = timedelta(minutes=last_route.service.type.duration)
        time_service = last_route.service.demand + time_delta

        if time_service > service.demand:
            return False

    return True


def find_nearest_technician(service, technicians):
    technician_nearest = None

    try:
        point_service = (float(service.client.latitude), float(service.client.longitude))
        min_distance = float('inf')

        for technician in technicians:
            last_service_position = search_current_technician_position(service, technician)

            if last_service_position is not None:
                point_technician = (float(last_service_position[0]), float(last_service_position[1]))
            else:
                point_technician = (float(technician.latitude), float(technician.longitude))

            distance = haversine(point_technician, point_service, unit=Unit.METERS)

            if distance < min_distance and evaluate_technician_availability(service, technician):
                min_distance = distance
                technician_nearest = technician
                print(technician)

        return technician_nearest

    except ValueError:
        return None


def add_service_route_technician(service, technician):
    route = Route(technician=technician,
                  service=service)
    route.save()


def worker_routes(queue_services):
    technicians = Technician.objects.all()

    while True:
        try:
            service = queue_services.get_nowait()
            technician_nearest = find_nearest_technician(service, technicians)

            if technician_nearest is not None:
                add_service_route_technician(service, technician_nearest)

        except Empty:
            break


def create_routes():
    technicians = Technician.objects.all()

    if len(technicians) > 0:
        cpus = cpu_count()
        print("#CPUs: ", cpus)
        date_now = datetime.now(tz=get_current_timezone())
        services = Service.objects.filter(demand__year=date_now.year,
                                          demand__month=date_now.month,
                                          demand__day=date_now.day,
                                          state__iexact='P').order_by('demand')

        Route.objects.filter(service__demand__gte=date_now).delete()
        processes = []
        print(services)

        if len(services) > 0:
            queue_services = Queue(len(services))

            for service in services:
                queue_services.put(service)

            #print("Queue Init ", queue_services.)

            '''p = Process(target=worker_routes, args=(queue_services,))
            p.start()
            p.join()'''

            for i in range(cpus):
                processes.append(Process(target=worker_routes, args=(queue_services,)))

            for process in processes:
                process.start()

            for process in processes:
                process.join()

routes/tests.py
from django.test import TestCase

# Create your tests here.

routes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic.base import View

from services.models import Service
from technicians.models import Technician
from datetime import datetime
from django.utils.timezone import get_current_timezone
from routes.models import Route
from django.contrib import messages


class ListRoutes(LoginRequiredMixin, View):
    login_url = '/'
    template_name = 'routes/routes.html'

    def get(self, request):
        date_now = datetime.now(tz=get_current_timezone())
        print(date_now)
        data_technicians = []
        technicians = Technician.objects.all()

        for technician in technicians:
            data_technician = {}
            routes = Route.objects.filter(technician=technician.id,
                                          created__year=date_now.year,
                                          created__month=date_now.month,
                                          created__day=date_now.day).order_by('service__demand')
            if len(routes) > 0:
                data_technician['id'] = technician.id
                data_technician['first_name'] = technician.user.first_name
                data_technician['routes'] = routes
                data_technicians.append(data_technician)

        print(data_technicians)
        return render(request,
                      self.template_name,
                      {'technicians': data_technicians})


class AttendService(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request, code_route):
        try:
            route = Route.objects.get(pk=code_route)
            service = Service.objects.get(pk=route.service.pk)
            service.state = 'F'
            service.save()
            messages.add_message(request, messages.INFO, "The service was attended successfully")

        except Route.DoesNotExist:
            messages.add_message(request, messages.ERROR, "The route does not exist")

        except Service.DoesNotExist:
            messages.add_message(request, messages.ERROR, "The service does not exist")

        list_routes = ListRoutes()
        return list_routes.get(request)

routes/templates/routes/routes.html
{% extends "users/base_users.html" %}
{% load static %}
{% load tz %}

{% block styles %}
{% endblock %}

{% block content %}
    {% include 'services/alerts.html' %}
    {% csrf_token %}
    <div class="page-header">
        <h1>
            <i class="fa fa-road page-header-icon"></i>
            <strong>&nbsp;&nbsp;Scheduled Routes</strong>
        </h1>
    </div> <!-- / .page-header -->

    <div class="row">
        <div class="col-md-12">
            <ul id="uidemo-tabs-default-demo" class="nav nav-tabs">
            {% for technician in technicians %}
                {% if forloop.first %}
                    <li class="active">
                {% else %}
                    <li>
                {% endif %}
                        <a href="#uidemo-tabs-{{ technician.id }}" data-toggle="tab">{{ technician.first_name }}</a>
                    </li>
            {% endfor %}
            </ul>

            <div class="panel">
                <div class="tab-content tab-content-bordered">
                {% for technician in technicians %}
                    {% if forloop.first %}
                    <div class="tab-pane fade active in" id="uidemo-tabs-{{ technician.id }}">
                    {% else %}
                    <div class="tab-pane fade" id="uidemo-tabs-{{ technician.id }}">
                    {% endif %}

                        <br>
                        <br>
                        <div class="timeline">
                            <!-- Timeline header -->
                            <div class="tl-header now bg-primary">Route Today</div>

                            {% for route in technician.routes %}
                                <div class="tl-entry">
                                    <div class="tl-time">
                                        {{ forloop.counter }}
                                    </div>

                                    <div class="panel tl-body">
                                        <h3 class="text-warning">{{ route.service.type.name }}</h3>
                                        <strong>Description of Service:</strong>&nbsp;{{ route.service.detail }}
                                        <br>
                                        <strong>Client:</strong> {{ route.service.client.user.first_name }}&nbsp;{{ route.service.client.user.last_name }}
                                        <br>
                                        <strong>Address:</strong> {{ route.service.client.address }}
                                        <br>
                                        <h4><strong>Date/Time for Service:</strong> {{ route.service.demand }}</h4>
                                        <br>
                                        {% if route.service.state == 'P' %}
                                            <a href="{% url 'routes:attend_service' route.id %}" class="btn btn-sm btn-rounded btn-primary">Attend</a>
                                        {% else %}
                                            <a href="" class="btn btn-sm btn-rounded btn-primary disabled">Attended</a>
                                        {% endif %}
                                    </div> <!-- / .tl-body -->
                                </div> <!-- / .tl-entry -->
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
                </div> <!-- / .tab-content -->
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        var init = [];
        init.push(function ()
        {
            $('#op_routes').addClass("active");
        });
        window.PixelAdmin.start(init);
    </script>

{% endblock %}