assign_service_routes/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from users.views import Login
from users.views import Logout


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),
    path('routes/', include('routes.urls', namespace="routes")),
    path('services/', include('services.urls', namespace="services")),
]

routes/urls.py
from django.urls import path
from routes.views import ListRoutes
from routes.views import AttendService

app_name = 'routes'

urlpatterns = [
    path('', ListRoutes.as_view(), name="list_routes"),
    path('attend-service/<int:code_route>/', AttendService.as_view(), name="attend_service"),
]

services/urls.py
from django.urls import path
from services.views import ListServices
from services.views import AddService

app_name = 'services'

urlpatterns = [
    path('', ListServices.as_view(), name="list_services"),
    path('add-service/', AddService.as_view(), name="add_service"),
]

services/models.py
from django.db import models
from clients.models import Client
from django.utils.translation import ugettext_lazy as _


STATE_SERVICE_CHOICES = (
    ('P', _(u"Pending")),
    ('A', _(u"Attending")),
    ('F', _(u"Finished")),
)


class TypeService(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    duration = models.PositiveIntegerField(default=0)

    def __str__(self):
        """Return username."""
        return self.name

    class Meta:
        verbose_name_plural = "Type Services"
        verbose_name = "Type Service"


class Service(models.Model):
    type = models.ForeignKey(TypeService, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    created = models.DateTimeField(
        'created at',
        auto_now_add=True,
        help_text='Date time on which the service was created.'
    )
    demand = models.DateTimeField(
        'demand service at',
        help_text='Date time on which the object was last modified.'
    )
    state = models.CharField(max_length=1, choices=STATE_SERVICE_CHOICES, default='P')
    detail = models.TextField(blank=True, null=True)

    def __str__(self):
        """Return username."""
        return "%s-%s %s" % (self.type.name, self.client.user.first_name, self.client.user.last_name)

    class Meta:
        verbose_name_plural = "Services"
        verbose_name = "Service"
        ordering = ['-demand', '-created']

services/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _
from services.models import Service


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ('type', 'client', 'demand', 'state', 'detail')

    def __init__(self, *args, **kwargs):
        super(ServiceForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

services/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic.base import View
from services.models import Service
from datetime import datetime
from django.utils.timezone import get_current_timezone
from services.forms import ServiceForm
from django.contrib import messages
from routes.create_routes import create_routes


class ListServices(LoginRequiredMixin, View):
    login_url = '/'
    template_name = 'services/services.html'

    def get(self, request):
        date_now = datetime.now(tz=get_current_timezone())
        services = Service.objects.filter(demand__year=date_now.year,
                                          demand__month=date_now.month,
                                          demand__day=date_now.day)
        return render(request,
                      self.template_name,
                      {'services': services})


class AddService(LoginRequiredMixin, View):
    login_url = '/'
    form_class = ServiceForm
    template_name = 'services/add_service.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        post = request.POST.copy()
        post['demand'] = str(post['demand']).replace("T", " ")
        date_service = datetime.strptime(str(post['demand']), '%Y-%m-%d %H:%M')
        date_now = datetime.now(date_service.tzinfo)

        if date_service > date_now:
            form = self.form_class(post)

            if form.is_valid():
                form.save()
                messages.add_message(request, messages.INFO, 'The Service was added successfully')

                if date_service.year == date_now.year and date_service.month == date_now.month and date_service.day == date_now.day:
                    create_routes()

            else:
                messages.add_message(request, messages.ERROR, 'The Service could not be added')

        else:
            messages.add_message(request, messages.ERROR, 'Services cannot be created on dates before the current one')

        return self.get(request)

services/templates/services/add_service.html
{% extends 'services/base_crud_service.html' %}

{% block title_form_service %}
    <i class="fa fa-plus-square page-header-icon"></i>&nbsp;Add Service
{% endblock %}

{% block button_action_service %}
    <button type="submit" class="btn btn-primary">Save</button>
{% endblock %}

services/templates/services/alerts.html
{%  load static %}
<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/sweetalert.css' %}">
<script src="{% static 'javascripts/jquery.js' %}"></script>
<script src="{% static 'javascripts/sweetalert.min.js' %}"></script>

<div id="alerts">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <script>
                    $(document).ready(function ()
                    {
                        swal(
                        {
                            type: "error",
                            title: "ERROR",
                            text: "{{ message }}",
                            showConfirmButton: true
                        });
                    })
                </script>

            {% else %}
                <script>
                    $(document).ready(function ()
                    {
                        swal(
                        {
                            type: "success",
                            title: "INFORMACIÓN",
                            text: "{{ message }}",
                            showConfirmButton: true
                        });
                    })
                </script>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

services/templates/services/base_crud_service.html
{% extends 'users/base_users.html' %}
{% load static %}
{% block styles %}
{% endblock %}

{% block content %}
    {% include 'services/alerts.html' %}
    <div class="page-header">
        <div class="row">
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-cogs page-header-icon"></i>
                <strong>&nbsp;&nbsp;Service Administration</strong>
            </h1>
        </div>
    </div>
    <div class="profile-full-name">
        <span class="text-semibold">
            {% block title_form_service %}
            {% endblock %}
        </span>
    </div>
    <div class="profile-row">
        <div class="left-col">
            <div class="profile-block">
                <div class="panel profile-photo">
                    <img src="{% static 'images/service.jpg' %}" alt="Photo Service">
                </div>
            </div>
        </div>
        <div class="right-col">
            <hr class="profile-content-hr no-grid-gutter-h">
            <div class="profile-content">
                <div class="panel">
                    <br><br>
                    <form method="post" id="form_service" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {% include 'services/form_service.html' %}
                        <br>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                {% block button_action_service %}
                                {% endblock %}
                                <a href="{% url 'services:list_services' %}">
                                    <button type="button" class="btn btn-danger">Cancel</button>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        init.push(function ()
        {
            var date = new Date()
            //var str_date = date.getDate().toString()
            $('body').addClass("page-profile");
            $('#op_services').addClass("active");
            $('#id_demand').attr('type', 'datetime-local')
            //$('#id_demand').val(str_date)
        });

        window.PixelAdmin.start(init);
    </script>

    {% block scripts_crud %}
    {% endblock %}
{% endblock %}

services/templates/services/form_service.html
{% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        <label for="jq-validation-url" class="col-sm-3 control-label">
            <strong>{{ field.label }}</strong>
        </label>
        <div class="col-sm-9">
            {{ field }}
        </div>
    </div>
{% endfor %}

services/templates/services/services.html
{% extends 'users/base_users.html' %}

{% block styles %}
{% endblock %}

{% block content %}
    {% include 'services/alerts.html' %}
    <div class="page-header">
        <div class="row">
            <!-- Page header, center on small screens -->
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-cogs page-header-icon"></i>
                <strong>&nbsp;&nbsp;Service Administration</strong>
            </h1>
            <div class="col-xs-12 col-sm-8">
                <div class="row">
                    <hr class="visible-xs no-grid-gutter-h">
                    <!-- "Create project" button, width=auto on desktops -->
                    <div class="pull-right col-xs-12 col-sm-auto">
                        <a href="{% url 'services:add_service' %}">
                            <button class="btn  btn-labeled btn-primary" >
                               <span class="btn-label icon fa fa-plus"></span>
                                Add Service
                            </button>&nbsp;&nbsp;
                        </a>
                    </div>
                    <!-- Margin -->
                    <div class="visible-xs clearfix form-group-margin"></div>
                    <!-- Search field -->
                </div>
            </div>
        </div>
    </div> <!-- / .page-header -->
    <!-- / Javascript -->
    <div class="panel">
        <div class="panel-body">
            <div class="table-primary">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="jq-datatables-example">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Type</th>
                            <th>Detail</th>
                            <th>Client</th>
                            <th>Address</th>
                            <th>Demand</th>
                            {#<th>Opciones</th>#}
                        </tr>
                    </thead>
                    <tbody>
                    {% for service in services %}
                        <tr class="odd gradeX">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ service.type.name }}</td>
                            <td>{{ service.detail }}</td>
                            <td>{{ service.client.user.first_name }}&nbsp;{{ service.client.user.last_name }}</td>
                            <td>{{ service.client.address }}</td>
                            <td>{{ service.demand }}</td>
                            {% comment %}<td>
                                <div class="btn-group" >
                                    <a href="" class="btn btn-primary">View</a>
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-caret-down"></i>
                                    </button>
                                    <ul class="dropdown-menu" style="z-index: 100 !important;">
                                        <li><a href="">Update</a></li>
                                        <li><a href="">Delete</a></li>
                                    </ul>
                                </div>&nbsp;
                            </td>{% endcomment %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        init.push(function ()
        {
            $('#jq-datatables-example').dataTable();
            $('#jq-datatables-example_wrapper .table-caption').text('List of Services');
            $('#jq-datatables-example_wrapper .dataTables_filter input').attr('placeholder', 'Find...');
        });
    </script>
{% endblock %}